modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ssblur/sip_of_sarsaparilla/issues"
license = "CC0-1.0"

[[mods]]
modId = "sipofsarsaparilla"
version = "${version}"
displayName = "Sip Of Sarsaparilla"
authors = "SSBlur"
description = '''
Bringing you a Sip of Sarsaparilla to keep you cool in this hot western sun.
'''
logoFile = "icon.png"

[[dependencies.sipofsarsaparilla]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sipofsarsaparilla]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sipofsarsaparilla]]
modId = "unfocused"
type = "required"
versionRange = "[${unfocused_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "sip_of_sarsaparilla.mixins.json"
